version: "3"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: meu_buzufba
      MONGO_INITDB_ROOT_PASSWORD: meu_buzufba
    volumes:
      - mongodb_data:/data/db
    networks:
      - meu_buzufba_network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: meu_buzufba
      ME_CONFIG_MONGODB_ADMINPASSWORD: meu_buzufba
      ME_CONFIG_MONGODB_URL: mongodb://meu_buzufba:meu_buzufba@mongo:27017/
      ME_CONFIG_BASICAUTH: false

    networks:
      - meu_buzufba_network

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: "--requirepass meu-buzufba"
    volumes:
      - redis:/data
    networks:
      - meu_buzufba_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: mongodb://meu_buzufba:meu_buzufba@mongo:27017/
      MONGODB_DATABASE: meu_buzufba
      JWT_SECRET_KEY: meu_secret_buzufba
      RESEND_API_KEY: ${RESEND_API_KEY}
      FRONTEND_URL: http://localhost:3000
      REDIS_URL: redis://default:meu-buzufba@redis:6379
    networks:
      - meu_buzufba_network

networks:
  meu_buzufba_network:
    driver: bridge

volumes:
  mongodb_data:
  redis:
    driver: local
