services:
  db:
    container_name: meu-buzufba-postgres
    image: bitnami/postgresql:latest
    env_file: ".env"
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - meu-buzufba-data:/bitnami/postgresql
    networks:
      - meu-buzufba-network

  cache:
    container_name: meu-buzufba-redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    networks:
      - meu-buzufba-network

  prometheus:
    image: prom/prometheus
    container_name: meu-buzufba-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - meu-buzufba-network

  grafana:
    image: grafana/grafana
    container_name: meu-buzufba-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - meu-buzufba-network

volumes:
  meu-buzufba-data:
	prometheus-data:

networks:
  meu-buzufba-network:
    driver: bridge
