services:
  db:
    container_name: ${APP_NAME}-postgres
    image: bitnami/postgresql:latest
    env_file: ".env"
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - meu-buzufba-data:/bitnami/postgresql
    networks:
      - meu-buzufba-network

  cache:
    container_name: ${APP_NAME}-redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    networks:
      - meu-buzufba-network

volumes:
  meu-buzufba-data:

networks:
  meu-buzufba-network:
    driver: bridge
