services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: db-meu-buzufba
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      - meu-buzufba

networks:
  meu-buzufba:
    driver: bridge

volumes:
  db:
